### ISSUE TITLE
homebirdge crash v0.3.0

### ISSUE THREAD

**Issue by electromitter** [SteidlD/homebridge-inkbird-bt-thsensor#2]
ReferenceError: Characteristic is not defined
    at new cInkbirdBtTHSensorAccessory (/usr/local/lib/node_modules/homebridge-inkbird-bt-thsensor/InkbirdBtTHSensorAccessory.js:109:54)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:356:50
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:329:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:155:12)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
[6/16/2020, 11:14:25] Got SIGTERM, shutting down Homebridge...
[6/16/2020, 11:14:33] [HB Supervisor] Homebridge Process Ended. Code

**Comment by SteidlD** [comment]
Upps. It seems that one of the other plugins installed on my homebridge defines Characteristic globally, so this doesn't happen on my system. But thats obviously a bug.. There's a new version of InkbirdBtTHSensorAccessory.js checked-in. Could you please change this file and give feedback if this solves the problem on your system. Then I will make a new official release 0.3.1 afterwards. Thanks

**Comment by electromitter** [comment]
it works now
